# Generated by Django 5.0.4 on 2024-05-20 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 20, 20, 6, 25, 616046, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(),
        ),
    ]
